# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/ntest18',
                'doc_host': 'https://hamelsmu.github.io',
                'git_url': 'https://github.com/hamelsmu/ntest18',
                'lib_path': 'ntest18'},
  'syms': {'ntest18.core': {'ntest18.core.foo': ('core.html#foo', 'ntest18/core.py')}}}